### ISSUE TITLE
lots of unused whitespace aroud the results, canyou remove that?

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-html#6] opened 2016-02-18 21:45 UTC

**Comment by tushar-rishav** [comment] 2016-02-18 21:53
@sils1297 Yeah. But it's not a bug in code. Probably, I have used 4 space indent rule for `test.py`. So changing the indent rule for test files would potentially fix it. I wonder what would happen if someone is following 8 space indent rule. I am sure no one would do that. :stuck_out_tongue_winking_eye:

**Comment by sils1297** [comment] 2016-02-18 22:02
this has nothing to do with the actual code, but you have sone padding or margin around the results which is just huge

**Comment by tushar-rishav** [comment] 2016-02-19 05:11
@sils1297 Are you talking about the indentation within code blocks or the wide margin between two code results? The latter is fixed by decreasing the margin.

**Comment by sils1297** [comment] 2016-02-19 10:00
the margin

**Closed** 2016-02-19 13:51 UTC
