### ISSUE TITLE
README.rst: Add setup instructions to README.md

### ISSUE THREAD

**Issue by KVGarg** [coala-analyzer/coala-html#152] opened 2019-01-11 18:16 UTC
Currently, in README.md there is no information provided on how to run coala-html on a project which makes difficult for a new contributor on how to and what commands should be used to run coala-html. 
So, need command instruction's with a small description what each command does to the README.md.
IMO we should add instructions from installing nodejs till the executing instruction of coala-html.
Make sure to use keyword `sudo` where needed in terminal commands.

This could be a suitable issue for newcomers.

**Comment by li-boxuan** [comment] 2019-01-12 01:39
Duplicate of https://github.com/coala/coala-html/issues/135

**Closed as completed by li-boxuan** 2019-01-12 01:39 UTC
